version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  # job 1 name
  build-and-test-and-deploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      # Specify the version you desire here
      - image: cimg/node:20.10.0
    # Add steps to the job
    steps:
      # Step 1: Checkout the code as the first step.
      - checkout

      # Step 2: Install dependencies and associated libraries
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: yarn

      # Step 3: run test if you have tests to run
      - run:
          name: Run tests
          command: yarn test

      # Step 4: Build
      - run:
          name: Run build
          command: yarn build
      # Step 5 - install Vercel CLI
      - run:
          name: Install Vercel CLI
          command: yarn global add vercel
      - run:
          name: Deploy to Vercel
          command: vercel --token $CHIMONEY_VERCEL_DEPLOYEMENT_TOKEN --prod

# Orchestrate jobs using workflows
workflows:
  # This is the name of the workflow, feel free to change it to better match your workflow.
  prod-build-test:
    jobs:
      - build-and-test-and-deploy
