name: Chimoney CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
        env:
          NEXT_PUBLIC_APIKEY: ${{ secrets.NEXT_PUBLIC_APIKEY }}
          NEXT_PUBLIC_AUTHDOMAIN: ${{ secrets.NEXT_PUBLIC_AUTHDOMAIN }}
          NEXT_PUBLIC_CHIMONEY_URL: ${{ secrets.NEXT_PUBLIC_CHIMONEY_URL }}
          NEXT_PUBLIC_CHIMONEY_API_KEY: ${{ secrets.NEXT_PUBLIC_CHIMONEY_API_KEY }}
          NEXT_PUBLIC_REDIRECT_URL: ${{ secrets.NEXT_PUBLIC_REDIRECT_URL }}
          NEXT_PUBLIC_PROJECTID: ${{ secrets.NEXT_PUBLIC_PROJECTID }}
          NEXT_PUBLIC_MESSAGINGSENDERID: ${{ secrets.NEXT_PUBLIC_MESSAGINGSENDERID }}
          NEXT_PUBLIC_STORAGEBUCKET: ${{ secrets.NEXT_PUBLIC_STORAGEBUCKET }}
          NEXT_PUBLIC_APPID: ${{ secrets.NEXT_PUBLIC_APPID }}

      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_APIKEY: ${{ secrets.NEXT_PUBLIC_APIKEY }}
          NEXT_PUBLIC_AUTHDOMAIN: ${{ secrets.NEXT_PUBLIC_AUTHDOMAIN }}
          NEXT_PUBLIC_CHIMONEY_URL: ${{ secrets.NEXT_PUBLIC_CHIMONEY_URL }}
          NEXT_PUBLIC_CHIMONEY_API_KEY: ${{ secrets.NEXT_PUBLIC_CHIMONEY_API_KEY }}
          NEXT_PUBLIC_REDIRECT_URL: ${{ secrets.NEXT_PUBLIC_REDIRECT_URL }}
          NEXT_PUBLIC_PROJECTID: ${{ secrets.NEXT_PUBLIC_PROJECTID }}
          NEXT_PUBLIC_MESSAGINGSENDERID: ${{ secrets.NEXT_PUBLIC_MESSAGINGSENDERID }}
          NEXT_PUBLIC_STORAGEBUCKET: ${{ secrets.NEXT_PUBLIC_STORAGEBUCKET }}
          NEXT_PUBLIC_APPID: ${{ secrets.NEXT_PUBLIC_APPID }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel --token=0noXWolESgsFH9HAtZk1EuzK --prod
